# Default values for picazzo pcells

from ipkiss.technology import get_technology
from ipkiss.technology.technology import TechnologyTree

TECH = get_technology()

TECH.PROCESS.HFW = TECH.PROCESS.NONE
TECH.PROCESS.SIL = TECH.PROCESS.SAL
TECH.PROCESS.P = TECH.PROCESS.P1
TECH.PROCESS.N = TECH.PROCESS.N1

############################################################################################
# Modulators
# 
# This file contains default settings for modulator devices
############################################################################################

TECH.MODULATORS = TechnologyTree()
TECH.MODULATORS.PHASESHIFTER = TechnologyTree()

# Defaults common to LAT and LONG PN junctions
TECH.MODULATORS.PHASESHIFTER.PN = TechnologyTree()
TECH.MODULATORS.PHASESHIFTER.PN.P_WIDTH = 2.0
TECH.MODULATORS.PHASESHIFTER.PN.PPLUS_OFFSET = 3.0
TECH.MODULATORS.PHASESHIFTER.PN.PPLUS_WIDTH = 2.0
TECH.MODULATORS.PHASESHIFTER.PN.PPLUS_EXTENSION = 0.25
TECH.MODULATORS.PHASESHIFTER.PN.N_WIDTH = 2.0
TECH.MODULATORS.PHASESHIFTER.PN.NPLUS_OFFSET = 3.0
TECH.MODULATORS.PHASESHIFTER.PN.NPLUS_WIDTH = 2.0
TECH.MODULATORS.PHASESHIFTER.PN.NPLUS_EXTENSION = 0.25
TECH.MODULATORS.PHASESHIFTER.PN.P_SIL_OFFSET = 3.2
TECH.MODULATORS.PHASESHIFTER.PN.P_SIL_WIDTH = 1.6
TECH.MODULATORS.PHASESHIFTER.PN.P_SIL_EXTENSION = 0.2
TECH.MODULATORS.PHASESHIFTER.PN.N_SIL_OFFSET = 3.2
TECH.MODULATORS.PHASESHIFTER.PN.N_SIL_WIDTH = 1.6
TECH.MODULATORS.PHASESHIFTER.PN.N_SIL_EXTENSION = 0.2
TECH.MODULATORS.PHASESHIFTER.PN.P_CONT_PITCH = 0.6
TECH.MODULATORS.PHASESHIFTER.PN.P_CONT_OFFSETS = [3.6, 4.2]
TECH.MODULATORS.PHASESHIFTER.PN.N_CONT_PITCH = 0.6
TECH.MODULATORS.PHASESHIFTER.PN.N_CONT_OFFSETS = [3.6, 4.2]
TECH.MODULATORS.PHASESHIFTER.PN.P_METAL1_OFFSET = 3.2
TECH.MODULATORS.PHASESHIFTER.PN.P_METAL1_WIDTH = 2.0
TECH.MODULATORS.PHASESHIFTER.PN.N_METAL1_OFFSET = 3.2
TECH.MODULATORS.PHASESHIFTER.PN.N_METAL1_WIDTH = 2.0
TECH.MODULATORS.PHASESHIFTER.PN.JUNCTION_OVERLAP = 0.0

# Lateral PN
TECH.MODULATORS.PHASESHIFTER.LATPN = TechnologyTree()
TECH.MODULATORS.PHASESHIFTER.LATPN.JUNCTION_OFFSET = 0.0
TECH.MODULATORS.PHASESHIFTER.LATPN.BRIDGE_WIDTH = 0.3
TECH.MODULATORS.PHASESHIFTER.LATPN.BRIDGE_PITCH = 1.0

# Longitudinal PN
TECH.MODULATORS.PHASESHIFTER.LONGPN = TechnologyTree()
TECH.MODULATORS.PHASESHIFTER.LONGPN.P_LENGTH = 0.3
TECH.MODULATORS.PHASESHIFTER.LONGPN.N_LENGTH = 0.3
TECH.MODULATORS.PHASESHIFTER.LONGPN.P_WIDTH = 3.2
TECH.MODULATORS.PHASESHIFTER.LONGPN.N_WIDTH = 3.2